version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - USER=user
      - PASSWORD=password
      - DB=data
      - HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - ./db/tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U data"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api_test:
    build: ./api-test
    tty: true
    volumes:
      - ./report:/etc/newman/newman